import {createClient, Entry} from 'contentful';
import {GetStaticProps} from 'next';
import Head from 'next/head';
import Link from 'next/link';
import * as React from 'react';

import {TechBlogModel} from '@/api/contentful/models/techBlog';

interface HomeContainerProps {
  articles: Array<Entry<TechBlogModel>>;
}

interface HomeProps {
  links: Array<{
    href: string;
    title: string;
  }>;
}

type ContainerProps = HomeContainerProps;

type Props = HomeProps;

const HomeContainer: React.FC<ContainerProps> = ({
  articles,
}) => {
  const links = React.useMemo(() => articles.map(({fields: {title, slug}}) => ({
    href: `/article/${slug}`,
    title,
  })), [articles]);

  return <Home links={links}/>;
};

const getStaticProps: GetStaticProps<ContainerProps> = async () => {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID ?? '',
    accessToken: process.env.CONTENTFUL_ACCESS_KEY ?? '',
  });

  const entry = await client.getEntries<TechBlogModel>({
    'content_type': 'techBlog',
    'limit': 10,
  });

  return {
    props: {
      articles: entry.items,
    },
  };
};

const Home: React.FC<Props> = ({links}) => {
  return (
    <div>
      <Head>
        <title>Tech Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Tech Blog
        </h1>

        {links.map(({href, title}) => (
          <Link key={href} href={href}>
            <a>{title}</a>
          </Link>
        ))}
      </main>
    </div>
  );
};

export type {HomeContainerProps, HomeProps};
export {getStaticProps};
export default HomeContainer;
